### ISSUE TITLE
Manifest file is missing or unreadable.

### ISSUE THREAD

**Issue by ghost** [ahmj/LeagueSets#1]
When I tried loading unpacked extension it tells me that it failed to load. I've never used this application before so I can't really tell what it is I'm doing wrong but I really want to use LeagueSets and if I could get some help that would be great.

**Comment by ahmj** [comment]
If you want to use the extension, visit the chrome store page (https://chrome.google.com/webstore/detail/leaguesets/eoekgdlembbelehimiljbdnofnldepmc) and click "Add to chrome" and it will install itself.

I think you might have confused yourself with the development instructions instead.

**Comment by ghost** [comment]
Oh, I thought that you had to do both. After I have it installed how do I launch it?
Edit: I found the instructions. Thanks for your help
