### ISSUE TITLE
Mobafire

### ISSUE THREAD

**Issue by Karuma** [ahmj/LeagueSets#2]
Hi 
I just tested Your chrome app on mobafire and it didn`t copy full build. It lost some items like Devourer, Duskblade or Oracle of Alteration.

Build Link: http://www.mobafire.com/league-of-legends/build/6-8-shyvana-jungle-total-guide-the-most-in-depth-427599#

json in zip file 
[jungle_dragon.zip](https://github.com/ahmj/LeagueSets/files/234290/jungle_dragon.zip)

**Comment by ahmj** [comment]
Hey,

Oops, I'll push out an update for mobafire / solomid in just a bit. The tables need a bit of updating. 

Thanks!

**Comment by ahmj** [comment]
Update is pushed out!

It may take some time for chrome to update your extension but you can do it manually if it hasn't already, by navigating to "chrome://extensions/" on your browser, check the box "Developer Mode" then click the button "Update extensions now" which will manually update your extensions.

Also the extension might need to be re-enabled as I've added a link to submit bugs but it required a new permission flag. 

Everything up to patch 6.7 should be included for mobafire.

**Comment by Karuma** [comment]
I maybe pain in the... but i have one more problem with json from mobafire.
http://www.mobafire.com/league-of-legends/build/s6-a-guide-to-jungle-sejuani-from-hell-450352
Its multi build, is it possible to separate them into two separate files, one file per build.
Also before build i heve list of Trinkets and Consumables, i know it maybe usefull for some ppl but some may not like it just like me ^^", i can remove it from file on my own but is it possible to add checkbox "add Trinkets and Consumables on bottom" ?

**Comment by Karuma** [comment]
Hi 
for mobafire its rly easy btw : 
mobafire.js
line 19 --> var title = $('.build-box:visible .build-title h2').text();
line 22 --> $('.build-box:visible .item-wrap').each(function (index) {

and you will get one build per click when its open; 
Sorry i have a lot work of my own, so look in your code, i hope you are not mad

**Comment by ahmj** [comment]
Great suggestions,

I've implemented both suggestions and they should be pushed out soon :)

**Comment by Karuma** [comment]
np :) so i stop my playing with checkbox now ^^"
