### ISSUE TITLE
New items not working

### ISSUE THREAD

**Issue by jblanchard1** [ahmj/LeagueSets#5]
Certain items in an item set on Mobafire are not appearing in the downloaded item set. The Control ward and Edge of Night were the items I tested / noticed. From a brief look at the code, it seems like the "tables" files might need to be updated to include the new items.

**Comment by ahmj** [comment]
Updated the mobafire table to include the recent changes :) The app should update in a couple of hours, or you can force the update through the extensions menu in chrome.

**Comment by jblanchard1** [comment]
Awesome!
